ci: freebsd-x64: compile with -Wno-missing-braces
The freebsd/latest image is still FreeBSD-12, with clang-8. It
generate false positive warnings:

../../foot/search.c:357:21: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    mbstate_t ps = {0};